{% set name = "pygtrie" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77700d2fcaab321ac65e86c2969fb4b64c116796baf52ab12d07de2e1f6cfc5d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - packaging
  run:
    - python

test:
  imports:
    - pygtrie

about:
  home: https://github.com/google/pygtrie
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python library implementing a trie data structure.
  doc_url: https://pygtrie.readthedocs.io/en/latest/
  dev_url: https://github.com/google/pygtrie

extra:
  recipe-maintainers:
    - Suor
    - efiop
    - shcheklein
